version: 2.1
orbs:
  discord: antonioned/discord@0.1.0

executors:
  cypress:
    docker:
      # Image primaire utilisée pour lancer les tests
      - image: cypress/browsers:node14.7.0-chrome84
        environment:
          ## this enables colors in the output
          TERM: xterm

jobs:
  unit-test:
    docker:
      - image: circleci/node:15
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache
            - ~/.config
            - ./node_modules
      - run: yarn test

  e2e-test:
    executor: cypress

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - restore_cache:
          keys:
            - e2e-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn ci:install
      - save_cache:
          key: e2e-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache
            - ~/.config
            - ./node_modules

      - run:
          command: yarn e2e:ci
          environment:
            MOCHA_FILE: /root/project/reports/test-results-[hash].xml

      - store_test_results:
          path: /root/project/reports/
      - store_artifacts:
          path: /root/project/reports/

      # Conserve les screenshots et la vidéo en cas d'erreur pour faciliter le debug
      - store_artifacts:
          path: cypress/videos
          when: on_fail
      - store_artifacts:
          path: cypress/screenshots
          when: on_fail

  deploy:
    docker:
      - image: circleci/node:15
    steps:
      - checkout
      - run: yarn global add caprover
      - run: yarn deploy
      - discord/status:
          success_only: true
          success_message: ":partying_face: Branch and Brush s'est déployé sans encombre ! :partying_face:"
          webhook: "${DISCORD_STATUS_WEBHOOK}"

filters-tag: &filters-tag
  branches:
    ignore: /.*/
  tags:
    only: /.*/

filters-all: &filters-all
  tags:
    only: /.*/

workflows:
  version: 2
  common:
    jobs:
      - unit-test :
          filters: *filters-all
      - e2e-test :
          filters: *filters-all
      - deploy:
          requires:
            - unit-test
            - e2e-test
          filters: *filters-tag
